name: Build AWS Infrastructure and Deploy Dockerized Flask-App on it.

on:
  # push:
  #   paths:
  #     - 'Terraform/**'
  #   branches: [ "main" ]

  workflow_dispatch: # Allow to run this workflow manually from the Actions tab
    inputs:
      trigger:
        description: "apply OR destroy" # apply to build infra, destroy to destroy it all.
        required: true
        default: apply # will choose the word apply for you when triggering the pipeline manually.
        type: choice
        options:
        - apply
        - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS User Credentials.
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS User Credentials.
  EC2_PRIVATE_SSH_KEY: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }} # Used to ssh into EC2.
  EC2_PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_PUBLIC_KEY }} # Used to upload public key to aws.
  TF_VAR_ami: ${{ secrets.TF_VAR_AMI }}  # trying different way to reference variables. we will use it in two jobs.
  AWS_REGION: us-east-1 
  #TRIGGER: 'apply' # Make it 'apply' to build AWS infra, and 'destroy' to destroy it all. "auto_workflow (on Push)"
  TRIGGER: '${{ inputs.trigger }}' # "manual workflow"

jobs:
  build-aws-infra:
    runs-on: ubuntu-latest
    
    outputs: 
      EC2_PRIVATE_IP: ${{ steps.get-private-ip.outputs.ec2_private_ip}} 
      BASTION_PUBLIC_IP: ${{ steps.get-public-ip.outputs.bastion_public_ip}}
       
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
 
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./Terraform
    
    # Checks that all Terraform configuration files in the correct format
    - name: Terraform Format
      run: |-
        terraform fmt -recursive
        terraform fmt -check
      working-directory: ./Terraform

    - name: Terraform ${{ env.TRIGGER }}
      id: apply-or-destroy # id only can have static name not changing name.
      run: |-
        terraform $TRIGGER \
        -var="public_key=$EC2_PUBLIC_SSH_KEY" \
        -var="key_name=ssh_key_aws" \
        -auto-approve
      working-directory: ./Terraform

    - name: Set Output 1
      if: env.TRIGGER == 'apply'
      id: get-private-ip
      run: echo "ec2_private_ip=$(terraform output application_private_ip_1)" >> $GITHUB_OUTPUT 
      working-directory: ./Terraform
   
    - name: Set Output 2
      if: env.TRIGGER == 'apply'
      id: get-public-ip
      run: echo "bastion_public_ip=$(terraform output bastion_public_ip)" >> $GITHUB_OUTPUT 
      working-directory: ./Terraform
      # echo "{name}={value}" >> $GITHUB_OUTPUT # new way of outputs


  
